#!/usr/bin/python
# This file is part of thunar-folder-thumbnailer.
#
# thunar-folder-thumbnailer is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Foobar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <https://www.gnu.org/licenses/>.

for a_file in ('set-folder-icon', ):
    with open(a_file, 'r') as f:
        data = f.read()

    sp = data.split('i18n')

    for n in sp:
        if n.startswith(' "'):
            l = n[2:].split('"')
            print('msgid "{}"\nmsgstr ""\n'.format(l[0]))
